# This file contains values from Cookiecutter

default_context:
  project_name: "fluentqa-base"
  project_plug: "fluentqa_base"
  project_description: "Awesome `fluentqa_base` is a Python cli/package "
  organization: "fluentqa-base"
  minimal_python_version: 3.10
  github_name: "fluent-qa"
  email: "hello@fluentqa-base.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "simple"
